version: "3.8"

services:
  mysql:
    image: mysql:5.5
    restart: always
    container_name: ilex-mysql
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ilex
      MYSQL_USER: ilex_user
      MYSQL_PASSWORD: ilex_pass
      MYSQL_ROOT_PASSWORD: root_pass

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ilex-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: ilex_user
      DB_PASSWORD: ilex_pass
      DB_NAME: ilex
      PORT: 3000
